In [1]:
import sys
sys.path.insert(0, "./../")

import os
import utils_modelling as utils

In [2]:
path_dataset = "./../../../dataset_used_split"
path_train = os.path.join(path_dataset, "train")
path_val = os.path.join(path_dataset, "val")
path_test = os.path.join(path_dataset, "test")

In [3]:
train_img, train_mask = utils.load_img_mask(path_train)
val_img, val_mask = utils.load_img_mask(path_val)
test_img, test_mask = utils.load_img_mask(path_test)

In [4]:
trainset = utils.create_dataset(train_img, train_mask)
valset = utils.create_dataset(val_img, val_mask)
testset = utils.create_dataset(test_img, test_mask)

In [5]:
unet_custom = utils.custom_unet()

In [6]:
unet_custom.compile(optimizer="adam",
                    loss="sparse_categorical_crossentropy",
                    metrics=["accuracy"])

In [7]:
unet_custom.fit(trainset,
                validation_data=valset,
                epochs=10)

Epoch 1/10
16/16 [==============================] - 35s 880ms/step - loss: nan - accuracy: 0.9202 - val_loss: nan - val_accuracy: 0.9824
Epoch 2/10
16/16 [==============================] - 7s 445ms/step - loss: nan - accuracy: 0.9825 - val_loss: nan - val_accuracy: 0.9824
Epoch 3/10
16/16 [==============================] - 7s 439ms/step - loss: nan - accuracy: 0.9825 - val_loss: nan - val_accuracy: 0.9824
Epoch 4/10
16/16 [==============================] - 7s 424ms/step - loss: nan - accuracy: 0.9825 - val_loss: nan - val_accuracy: 0.9824
Epoch 5/10
16/16 [==============================] - 7s 405ms/step - loss: nan - accuracy: 0.9825 - val_loss: nan - val_accuracy: 0.9824
Epoch 6/10
16/16 [==============================] - 7s 404ms/step - loss: nan - accuracy: 0.9825 - val_loss: nan - val_accuracy: 0.9824
Epoch 7/10
16/16 [==============================] - 7s 401ms/step - loss: nan - accuracy: 0.9825 - val_loss: nan - val_accuracy: 0.9824
Epoch 8/10
16/16 [=============================

In [8]:
import matplotlib.pyplot as plt

for images, masks in trainset.take(9):
    print(masks[0])
    print(len(masks))
    # for i in range(3):
    #     plt.subplot(1, 3, i + 1)
    #     plt.imshow(images[i])
    #     plt.imshow(masks[i], alpha=0.5)
    # plt.show()
    break

tf.Tensor(
[[[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]], shape=(128, 128, 1), dtype=int32)
16
